// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package balance

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
	time "time"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson4f4a6fc6DecodeDiploma1InternalAppServiceBalance(in *jlexer.Lexer, out *WithdrawOrderList) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(WithdrawOrderList, 0, 2)
			} else {
				*out = WithdrawOrderList{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 WithdrawOrder
			(v1).UnmarshalEasyJSON(in)
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4f4a6fc6EncodeDiploma1InternalAppServiceBalance(out *jwriter.Writer, in WithdrawOrderList) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			(v3).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v WithdrawOrderList) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4f4a6fc6EncodeDiploma1InternalAppServiceBalance(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v WithdrawOrderList) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4f4a6fc6EncodeDiploma1InternalAppServiceBalance(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *WithdrawOrderList) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4f4a6fc6DecodeDiploma1InternalAppServiceBalance(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *WithdrawOrderList) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4f4a6fc6DecodeDiploma1InternalAppServiceBalance(l, v)
}
func easyjson4f4a6fc6DecodeDiploma1InternalAppServiceBalance1(in *jlexer.Lexer, out *WithdrawOrder) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "order":
			out.OrderNumber = int(in.Int())
		case "sum":
			out.Sum = float64(in.Float64())
		case "processed_at":
			if in.IsNull() {
				in.Skip()
				out.Date = nil
			} else {
				if out.Date == nil {
					out.Date = new(time.Time)
				}
				if data := in.Raw(); in.Ok() {
					in.AddError((*out.Date).UnmarshalJSON(data))
				}
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4f4a6fc6EncodeDiploma1InternalAppServiceBalance1(out *jwriter.Writer, in WithdrawOrder) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"order\":"
		out.RawString(prefix[1:])
		out.Int(int(in.OrderNumber))
	}
	{
		const prefix string = ",\"sum\":"
		out.RawString(prefix)
		out.Float64(float64(in.Sum))
	}
	{
		const prefix string = ",\"processed_at\":"
		out.RawString(prefix)
		if in.Date == nil {
			out.RawString("null")
		} else {
			out.Raw((*in.Date).MarshalJSON())
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v WithdrawOrder) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4f4a6fc6EncodeDiploma1InternalAppServiceBalance1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v WithdrawOrder) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4f4a6fc6EncodeDiploma1InternalAppServiceBalance1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *WithdrawOrder) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4f4a6fc6DecodeDiploma1InternalAppServiceBalance1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *WithdrawOrder) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4f4a6fc6DecodeDiploma1InternalAppServiceBalance1(l, v)
}
